#  _  ___ _   _         
# | |/ (_) |_| |_ _   _ 
# | ' /| | __| __| | | |
# | . \| | |_| |_| |_| |
# |_|\_\_|\__|\__|\__, |
#                 |___/ 
# by Frogprog (2025)

font_family    Hack Nerd Font
font_size 		20.0
bold_font       auto
italic_font      auto
bold_italic_font auto

confirm_os_window_close 0

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 0

shell_integration no-cursor

# block / beam / underline
cursor_shape block

# --- Цвета Gruvbox Light Forest ---

# Базовая подложка (Gruvbox Bone)
background            #f9f5d7
foreground            #3c3836

# Цвет курсора и выделения
cursor                #689d6a
selection_background  #ebdbb2
selection_foreground  #3c3836

# Цветовая палитра (ANSI)
# Black (Dark Grey)
color0  #282828
color8  #928374

# Red
color1  #cc241d
color9  #fb4934

# Green (Твой основной акцент)
color2  #689d6a
color10 #79740e

# Yellow
color3  #d79921
color11 #fabd2f

# Blue
color4  #458588
color12 #83a598

# Magenta
color5  #b16286
color13 #d3869b

# Cyan
color6  #689d6a
color14 #8ec07c

# White
color7  #a89984
color15 #fbf1c7

# --- Настройки окна ---

# Убираем закругления, как в Waybar и Obsidian
window_margin_width 0
window_border_width 0
draw_minimal_borders yes
