#  ████     ████     ██     ████     ██   ████████    ███████
# ░██░██   ██░██    ████   ░██░██   ░██  ██░░░░░░██  ██░░░░░██
# ░██░░██ ██ ░██   ██░░██  ░██░░██  ░██ ██      ░░  ██     ░░██
# ░██ ░░███  ░██  ██  ░░██ ░██ ░░██ ░██░██         ░██      ░██
# ░██  ░░█   ░██ ██████████░██  ░░██░██░██    █████░██      ░██
# ░██   ░    ░██░██░░░░░░██░██   ░░████░░██  ░░░░██░░██     ██
# ░██        ░██░██     ░██░██    ░░███ ░░████████  ░░███████
# ░░         ░░ ░░      ░░ ░░      ░░░   ░░░░░░░░    ░░░░░░░
#
#               MAIN CONFIGURATION FILE
#
#                           by Frogprog (https://github.com/FrogProg09/)
#                           year 2026

# Wiki: https://mangowm.github.io/docs/

# source files

source=./display.conf
source=./input.conf
source=./window.conf
source=./keybind.conf
source=./on-startup.conf
