#               MONITOR CONFIGURATION FILE
#
#                           by Frogprog (https://github.com/FrogProg09/)
#                           year 2026

# Wiki: https://mangowm.github.io/docs/configuration/monitors

# My eDP laptop monitor
monitorrule=name:^eDP-1$,width:1920,height:1080,refresh:60,x:0,y:0
