#               STARTUP CONFIGURATION FILE
#
#                           by Frogprog (https://github.com/FrogProg09/)
#                           year 2026

# Wiki: https://mangowm.github.io/docs/configuration/basics

# Utilities that are supposed to start on startup

# bar
exec-once=waybar
# background image
exec-once=swaybg -i ~/.config/wallpapers/quiet_babushkas_rug.png
# notification center
exec-once=swaync
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once=/usr/lib/xdg-desktop-portal-wlr
# emacs server
exec-once=emacs --daemon &

# disable laptop monitor on startup
exec-once=wlr-randr --output HDMI-A-2 --mode 1920x1080@120
exec-once=mmsg dispatch disable_monitor,eDP-1
