# Utilities that are supposed to start on starup

exec-once=waybar
exec-once=swaybg -i ~/.config/wallpapers/quiet_babushkas_rug.png
exec-once=swaync
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once=/usr/lib/xdg-desktop-portal-wlr
exec-once=emacs --daemon &
